tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "asciinema"
brew "bandwhich"
brew "bat"
brew "cmus"
brew "coreutils"
brew "ctop"
brew "curl"
brew "delve"
brew "deno"
brew "diff-so-fancy"
brew "duf"
brew "exa"
brew "exiftool"
brew "fdupes"
brew "figlet"
brew "fzf"
brew "git"
brew "gitmoji"
brew "glances"
brew "gnupg"
brew "go"
brew "gping"
brew "hugo"
brew "hyperfine"
brew "inxi"
brew "just"
brew "lazydocker"
brew "lazygit"
brew "magic-wormhole"
brew "mas"
brew "most"
brew "navi"
brew "neofetch"
brew "neovim"
brew "nnn"
brew "pinentry-mac"
brew "procs"
brew "ripgrep"
brew "rsync"
brew "scc"
brew "sd"
brew "starship"
brew "tealdeer"
brew "thefuck"
brew "tmate"
brew "tmux"
brew "tokei"
brew "tree"
brew "xsel"
brew "youtube-dl"
brew "zoxide"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"
cask "alfred"
cask "balenaetcher"
cask "brave-browser"
cask "cheatsheet"
cask "discord"
cask "downie"
cask "dropbox"
cask "dropzone"
cask "font-jetbrains-mono-nerd-font"
cask "font-maple"
cask "google-drive"
cask "iina"
cask "keycastr"
cask "makemkv"
cask "mullvadvpn"
cask "mymonero"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "permute"
cask "plex"
cask "proton-drive"
cask "signal"
cask "steam"
cask "syncthing"
cask "tailscale"
cask "transmission"
cask "wezterm"
mas "Affinity Photo", id: 824183456
mas "Bible Study", id: 472790630
mas "DaisyDisk", id: 411643860
mas "Encrypto", id: 935235287
mas "Kindle", id: 302584613
mas "Magnet", id: 441258766
mas "Quiver", id: 866773894
mas "Recipe Keeper", id: 1315583175
mas "WiFi Explorer", id: 494803304
